# defining some unit proxy references, mostly for making it
# easier to make global changes later
units:
  # for spacing of keycaps
  kx: cx
  ky: cy
  # for padding between keycaps
  px: kx + 2
  py: ky + 2
points:
  rotate: -13.5
  mirror: &mirror
    ref: thumb_aux_main
    distance: 22
  zones:
    main:
      anchor:
        # for positioning in KiCad
        shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          key.column_net: P113
        pinky:
          key.column_net: P111
        ring:
          key:
            spread: u
            column_net: P010
        middle:
          key:
            spread: u
            column_net: P009
        index:
          key:
            spread: u
            column_net: P011
        inner:
          key.column_net: P104
      rows:
        bottom:
          row_net: P002
          mirror.row_net: P024
        home:
          row_net: P029
          mirror.row_net: P022
        top:
          row_net: P031
          mirror.row_net: P008
    thumb:
      key: 
        padding: 1ky
        spread: 1kx        
      anchor:
        ref: main_outer_bottom
        shift: [1.5kx, -ky]
      rows:
        main:
          row_net: P115
          mirror.row_net: P100
      columns:
        mod4:
          key.column_net: P113
        mod3:
          key.column_net: P111
        mod2:
          key.column_net: P010
        mod1:
          key:
            splay: -10
            spread: kx+2
            stagger: -2
            column_net: P009
        primary:
          key:
            splay: 70
            spread: kx+5
            stagger: 1
            width: 1.5kx
            column_net: P011
        aux:
          key:
            splay: 30
            spread: kx+8
            stagger: 6
            column_net: P104
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      # starting at top-left of board, going counter clockwise
      # and shifting points to edge of key
      points:
        - ref: main_outer_top
          shift: [-0.5px, 0.5py]
        - ref: main_outer_bottom
          shift: [-0.5px, -0.5py]
        - ref: thumb_mod4_main
          shift: [-0.5px, -0.5py]
        - ref: thumb_mod1_main
          shift: [-0.5px, -0.5py]
        - ref: thumb_primary_main
          shift: [-0.75px, -0.75py]
        - ref: mirror_thumb_primary_main
          shift: [-0.75px, -0.75py]
        - ref: mirror_thumb_mod1_main
          shift: [-0.5px, -0.5py]
        - ref: mirror_thumb_mod4_main
          shift: [-0.5px, -0.5py]
        - ref: mirror_main_outer_bottom
          shift: [-0.5px, -0.5py]
        - ref: mirror_main_outer_top
          shift: [-0.5px, 0.5py]
        - ref: mirror_main_index_top
          shift: [-0.5px, 0.5py]
        - ref: main_index_top
          shift: [-0.5px, 0.5py]
  combo:
    - name: board
    - operation: subtract
      name: keys
      
pcbs:
  elv:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        adjust:
          shift: [0, -5]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      nicenano:
        what: nice_nano
        params: {}
        where:
          ref.aggregate.parts: [main_inner_top, mirror_main_inner_top]
          shift: [0, -3]
          rotate: -90      
      niceview:
        what: nice_view
        params:
          SDA: P017
          SCL: P020
          CS: P006
        where:
          ref.aggregate.parts: [main_inner_home, mirror_main_inner_home]
          shift: [0, -6]
          rotate: 90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref.aggregate.parts: [main_index_top, mirror_main_index_top]
          shift: [-16, 7]
      battery:
        what: jstph
        params:
          pos: BAT
          neg: GND
          side: F
        where:
          ref.aggregate.parts: [main_index_top, mirror_main_index_top]
          shift: [24, 8.5]
          rotate: -90
      powerswitch:
        what: slider
        where:
          ref.aggregate.parts: [main_index_top, mirror_main_index_top]
          shift: [31, 9]
        params:
          from: RAW
          to: BAT
          side: B          
